<?php
// Variables
return [
  "creatorName" => "pulak",
  "creatorUrl" => "#",
  "templateName" => "PULAK",
  "templateSuffix" => "ERP SOFTWARE",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "Laravel 12 with Bootstrap 5 Powerful ERP SOFTWARE.",
  "templateKeyword" => "LIVEWIRE",
  "licenseUrl" => "#",
  "livePreview" => "#",
  "productPage" => "#",
  "ogTitle" => "Erp software",
  "ogType" => "product",
  "ogImage" => "#",
  "support" => "#",
  "moreThemes" => "#",
  "documentation" => "#",
  "repository" => "#",
  "gitRepo" => "#",
  "gitRepoAccess" => "#",
  "githubFreeUrl" => "#",
  "facebookUrl" => "#",
  "twitterUrl" => "#",
  "githubUrl" => "#",
  "dribbbleUrl" => "#",
  "instagramUrl" => "#"
];
